name: Deploy Ours Album Server

on:
  push:
    branches:
      - main
    paths:
      - server/**
      - .github/workflows/deployServerToOwnServer.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload repo to own server and build server
        uses: appleboy/ssh-action@master
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CONNECTION_URL,JWT_SECRET
          script: |
            if [ ! -d "./server/Ours-Album" ]; then
              cd  ./server
              git clone https://github.com/Ligengxin96/Ours-Album.git
              cd ./Ours-Album/server
            else 
              cd ./server/Ours-Album/server
              git pull
            fi
            docker stop ours-album || true && docker container rm ours-album || true && docker image rm ours-album -f || true
            docker build -t ours-album .
            docker run -e CONNECTION_URL=$CONNECTION_URL -e JWT_SECRET=$JWT_SECRET -p 5000:5000 --net userDefined --ip 172.20.0.3 --restart=always -d --name ours-album ours-album
